// This file is autogenerated by scripts/build-preview-imports.ts
// Do not edit this file directly.
import type { DocsConfig } from "@/types/docs";

export const docsConfig: DocsConfig = {
  nav: [
    {
      title: "Getting Started",
      slug: "docs",
      items: [
        { title: "Introduction", href: "/docs/introduction" },
        { title: "About", href: "/docs/about" },

      ]
    },
    {
        title: "Workshops",
        slug: "workshops",
        items: [
          { title: "DEI", href: "/workshops/DEI" },
          { title: "Enlightened Self Interest", href: "/workshops/Enlightened-Self-Interest" },
          { title: "Leadership", href: "/workshops/leadership" },
          { title: "Organization Culture", href: "/workshops/organization-culture" },
          { title: "Social Responsibility", href: "/workshops/social-responsibility" },
          { title: "Stewardship", href: "/workshops/stewardship" },
          { title: "Values, Ethics, Virtue", href: "/workshops/values-ethics-virtue" },

        ]
      },
      {
        title: "Mentoring",
        slug: "mentoring",
        items: [
          { title: "Mind Mastery", href: "/mentoring/mind-mastery" },
          { title: "Restart", href: "/mentoring/restart" },
          { title: "ROI", href: "/mentoring/roi" },
          { title: "Self Actualizing", href: "/mentoring/self-actualizing" },
          { title: "Unparalleled Leadership", href: "/mentoring/unparalleled-leadership" },

        ]
      },
      {
        title: "Speaking",
        slug: "speaking",
        items: [
          { title: "Keynote, Seminars, Training", href: "/speaking/keynote-seminar-training" },

        ]
      },
      {
        title: "Books",
        slug: "books",
        items: [
          { title: "Engaging the Heart for People Performance and Profit", href: "/books/Engaging-the-Heart-for-People-Performance-and-Profit" },
          { title: "Recognizing and Rewarding Employees", href: "/books/Recognizing-and-Rewarding-Employees" },
          { title: "Back to a New Normal", href: "/books/Back-to-a-new-normal" },
          { title: "Compassion in Action", href: "/books/Compassion-in-action" },

        ]
      },
      {
        title: "EZWorks",
        slug: "ezworks",
        items: [
          { title: "Is the somking gun of anger killing your business?", href: "/ezworks/anger" },
          { title: "When bad things happen to good managers", href: "/ezworks/manager" },

        ]
      },
  ]
};
